### PR TITLE
Release: NWPS-1648 - Anchor link dynamic heading amendments

### PR DESCRIPTION
**Pull request by AlexKirstenZA**
@smanivasag @sankar-shunmuga @FranciscoRuizHEE 

Content editors can specify which heading types (h2, h3, h4 etc) they would like to use to generate the anchor links, and the javascript code generates the links accordingly.

However, it was generating links from every block found within the content area, including tabs etc. whereby you cannot actually see the heading until you show / hide the content.

This fix ensure that only headings found within rich text are used to generate the anchor links, and no headings within components are included, as per the tickets spec.

Please shout if anything is unclear.

Thanks!

### CODE REVIEW

**Review by smanivasag — COMMENTED** [review]
@AlexKirstenZA - Thanks for the PR and the elegant solution to a complex problem (at least looking at the way the issue has been described in the ticket) 😄 👍 

There are a couple of observations:
- The fix seems to include the `<h2>` from the `Region picker` block as it currently doesn't seem to have been wrapped within a block's container element i.e. it's exposed directly under `page__content`. Since this is an exceptional case, I am happy to include the `data-anchorlinksignore="true"` attribute for the Region picker `<h2>` to ignore it for now. How does that sound ?
- The component seems to render an empty block when there are no matching headings under `page__content`. Could we hide the block during these scenarios ?

Thank you!

**Comment by AlexKirstenZA** [comment]
Hey @smanivasag,

Nice find with the region component, thanks for that! 

I've gone ahead and wrapped the component macro with a div using the correct prefix of `hee-navmap` :+1: 

Also, I've pushed a fix for hiding the anchorlinks when there are no headings available.

Thanks :slightly_smiling_face:

**Review by smanivasag — COMMENTED** [review]
@AlexKirstenZA - Thanks for the fixes 👍 

Just wondering if we can remove the following line:
```
File: app/assets/hee/blocks/content/sidebar/hee-anchorlinks/anchorlinks.js
72:       this.anchorLinks.hidden = false;
```
as it has already been covered by:
```
File: app/assets/hee/blocks/content/sidebar/hee-anchorlinks/anchorlinks.js
19:         this.anchorLinks.hidden = false;
```

Thanks!

**Review by smanivasag — APPROVED** [review]
@AlexKirstenZA - Thanks for the fix and approved 👍

**Pull request merged**
